language: java
dist: trusty
jdk:
- openjdk8
- openjdk7
install: JAVA_HOME=$(jdk_switcher home openjdk8) ./gradlew dependencies -PossrhUsername=username
  -PossrhPassword=password
script: ./gradlew test -PossrhUsername=username -PossrhPassword=password
before_deploy:
- openssl aes-256-cbc -K $encrypted_fd9e12525773_key -iv $encrypted_fd9e12525773_iv
  -in secring.gpg.enc -out secring.gpg -d
deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew uploadArchives -PossrhUsername="${MVN_USERNAME}" -PossrhPassword="${MVN_PASSWORD}" -Psigning.keyId="${SIGNING_KEY_ID}" -Psigning.password="${SIGNING_PASSWORD}" -Psigning.secretKeyRingFile="${SIGNING_SECRET_KEY_RING_FILE}"
  on:
    tags: true
    branch: master
